/**
 * Type definitions for Analytics Service
 * Used internally for LLM prompting, metrics calculation, and database persistence
 */

// ============================================================================
// METRICS SNAPSHOTS
// ============================================================================

/**
 * Raw metrics extracted from a single week of child data
 * Used as input to LLM for generating insights
 */
export interface MetricsSnapshot {
  storiesCount: number; // Total stories completed this week
  challenges: {
    [type: string]: number; // Breakdown by challenge type (RIDDLE, MULTIPLE_CHOICE, etc.)
  };
  successRate: number; // Percentage (0-100) of correct answers
  hintUsagePattern: {
    totalHintsUsed: number;
    averageHintsPerChallenge: number;
  };
  timeSpent: {
    totalSeconds: number; // Total active time in seconds
    averagePerStory: number; // Average seconds per story
  };
  skillsExercised: string[]; // Skill categories worked on (logic, vocabulary, comprehension, etc.)
  difficultiesHandled: number[]; // Array of difficulty levels (1-5) encountered
  challengeResultBreakdown?: {
    correct: number;
    incorrect: number;
    skipped: number;
  };
}

/**
 * Trend analysis comparing two weeks
 * Used in LLM prompt for progress narrative
 */
export interface TrendAnalysis {
  successRateChange: number | null; // Percentage change, null if no previous week
  hintUsageImprovement: number | null; // Negative means fewer hints (improvement)
  speedImprovement: number | null; // Percentage faster, null if no previous week
  difficultyProgression: number | null; // Highest difficulty this week - highest prev week
  newSkillsIntroduced: string[]; // Skills not exercised previous week
  strugglingAreas: string[]; // Skills with lower performance
  improvementAreas: string[]; // Skills with improved performance
  velocityChange: "improving" | "consistent" | "regressing" | null;
}

// ============================================================================
// LLM INPUT/OUTPUT
// ============================================================================

/**
 * Input prepared for the LLM to generate analytics
 * Combines all context needed for comprehensive analysis
 */
export interface AnalyticsInput {
  childName: string;
  childAge: string; // "6", "7", "8", etc.
  favoriteThemes: string[];
  // learningObjectives: string[];
  currentSkillScores: {
    [skillName: string]: {
      score: number; // 0.0-1.0
      confidence: number;
    };
  };
  thisWeekMetrics: MetricsSnapshot;
  previousWeekMetrics?: MetricsSnapshot;
  trendAnalysis?: TrendAnalysis;
}

/**
 * Output generated by the LLM
 * Structured narrative with executive summary, trends, and recommendations
 */
export interface AnalyticsOutput {
  executiveSummary: string; // TL;DR: max ~150 words
  progressTrends: string; // Comparison with previous week: max ~200 words
  recommendations: string[]; // Actionable parent suggestions: max 5 items
}

// ============================================================================
// DATABASE MODEL (mirrors Prisma WeeklyAnalyticsReport)
// ============================================================================

/**
 * Complete weekly analytics report saved to database
 * Structure mirrors WeeklyAnalyticsReport Prisma model
 */
export interface WeeklyAnalyticsReportData {
  id?: string; // Generated by database
  childProfileId: string;
  week: number;
  executiveSummary: string;
  progressTrends: string;
  recommendations: string[];
  metricsSnapshot: MetricsSnapshot; // Store raw metrics for debugging
  createdAt?: Date;
  updatedAt?: Date;
}

// ============================================================================
// SERVICE RESPONSES
// ============================================================================

/**
 * Response from generateWeeklyReport service
 * Used by controller to return to client
 */
export interface GenerateReportResponse {
  success: boolean;
  reportId?: string;
  childProfileId: string;
  week: number;
  executiveSummary: string;
  progressTrends: string;
  recommendations: string[];
  generatedAt: Date;
  error?: string;
}
